### ISSUE TITLE
Fix handling of spaces in sets

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/EDTF#59]
`{ ..1983}` is currently incorrectly interpreted as `{0..1983}`

`{ ..1983}` should be interpreted as `{..1983}`

**Comment by chaudbak** [comment]
Could you please specify which API method you use and observe invalid outcome? What is meant by 'interpreted as {0..1983}'
And one more thing: `$parser->parse({ ..1983})` doesn't accept this value at all and throws `Invalid edtf format` exception (because of spaces). Is it acceptable behaviour?

**Comment by JeroenDeDauw** [comment]
![image](https://user-images.githubusercontent.com/146040/115060138-caae8100-9ee7-11eb-97ed-f6c951011017.png)

> And one more thing: `$parser->parse({ ..1983})` doesn't accept this value at all and throws `Invalid edtf format` exception (because of spaces). Is it acceptable behaviour?

Are you saying that is the current behavior? It does not seem to be, as per the screenshot. Ideally `{ ..1983}` is understood to be `{..1983}`, though if an exception is thrown when the space is there, that is also fine.

**Comment by chaudbak** [comment]
Yes, exactly. That's the current behavior. I am not sure how the data presented on the screenshot is built, but I think it doesn't throws the exception, because it goes only through Humanizer which doesn't trigger Parser's `parse` method

Thanks for the explanation and the screenshot. Now it's clear that it's about the wrong humanization

**Comment by JeroenDeDauw** [comment]
@chaudbak so you can fix this now right?
