### ISSUE TITLE
Avoid Capitalisation of beginning of humanisation

### ISSUE THREAD

**Issue by mzeinstra** [ProfessionalWiki/EDTF#87]
Interesting suggestion by @verdy-p that will increase the usability of this repo:

 > avoid forcing a leading capital in sources (e.g. "from $1 to $2" and not "From $1 to $2", "yesterday" and not "Yesterday"...) and that all translations should use uncapitalized terms (unless these terms are always capitalized like "Monday" or "March" in English), i.e. like entries in dictionaries. The capitalisation at start of a sentence or title can be inferred. CLDR does not force the capitalisation in any one of these translatable terms.

_Originally posted by @verdy-p in https://github.com/ProfessionalWiki/EDTF/issues/77#issuecomment-1383118533_

**Comment by JeroenDeDauw** [comment]
Do you have an example of a message for which this is currently going wrong?

**Comment by verdy-p** [comment]
E.g. in French: forced capitalization is wrong on almost every part of formatted dates (including but not limited to month names, weekday names, season names), except some parts for era names citing proper names (Jesus-Christ, Buddha, Japanese emperors...), but not derived terms like adjectives (like "chrétien(ne)", "bouddhiste", "musulman(e)", "islamique"). Forced capitalization is wrong for ordinals (like "premier", "deuxième", ...), and for all prepositions (like "de", "à", "vers", ...) and adverbs (like "environ", "approximativement", ...)

**Comment by JeroenDeDauw** [comment]
Yeah ok. So what is an example of those rules being violated by the current implementation?

Any of the translations in here wrong? https://github.com/ProfessionalWiki/EDTF/blob/master/tests/Functional/FrenchHumanizationTest.php

**Comment by verdy-p** [comment]
```
-		yield 'Leading zeroes' => [ '0042', 'Année 42' ];
+		yield 'Leading zeroes' => [ '0042', 'année 42' ];

-		yield 'Interval with open end' => [ '2019/..', 'Depuis 2019 (fin indéterminée)' ];
+		yield 'Interval with open end' => [ '2019/..', 'depuis 2019 (fin indéterminée)' ];

-		yield 'Interval with open start' => [ '../2021', 'Jusqu’à 2021' ];
+		yield 'Interval with open start' => [ '../2021', 'Jusqu’en 2021' ];

-		yield 'Interval with unknown end' => [ '2019/', 'Depuis 2019 jusqu’à une fin inconnue' ];
+		yield 'Interval with unknown end' => [ '2019/', 'depuis 2019 jusqu’à une fin inconnue' ];

-		yield 'Interval with unknown start' => [ '/2021', 'Depuis un début inconnu jusqu’à 2021' ];
+		yield 'Interval with unknown start' => [ '/2021', 'depuis un début inconnu jusqu’en 2021' ];

-		yield 'Year approximate' => [ '2019~', 'Autour du 2019' ];
+		yield 'Year approximate' => [ '2019~', 'autour de 2019' ]; //or:
+		yield 'Year approximate' => [ '2019~', 'en 2019 environ' ];

-		yield 'Year uncertain approximation' => [ '2019%', 'Autour du 2019 (incertain)' ];
+		yield 'Year uncertain approximation' => [ '2019%', 'autour de 2019 (incertain)' ]; // or:
+		yield 'Year uncertain approximation' => [ '2019%', 'en 2019 environ (incertain)' ]; // or:
+		yield 'Year uncertain approximation' => [ '2019%', 'vers 2019 (incertain)' ]; // or:

-		yield 'Month approximate' => [ '2019-04~', 'Autour du Avril 2019' ];
+		yield 'Month approximate' => [ '2019-04~', 'autour d’avril 2019' ]; //or:
+		yield 'Month approximate' => [ '2019-04~', 'en avril 2019 environ' ]; //or:
+		yield 'Month approximate' => [ '2019-04~', 'vers avril 2019' ];

-		yield 'Month uncertain' => [ '2019-04?', 'Avril 2019 (incertain)' ];
+		yield 'Month uncertain' => [ '2019-04?', 'avril 2019 (incertain)' ];

-		yield 'Day approximate' => [ '2019-04-01~', 'Autour du 1er avril 2019' ];
+		yield 'Day approximate' => [ '2019-04-01~', 'autour du 1er avril 2019' ]; //or:
+		yield 'Day approximate' => [ '2019-04-01~', 'vers le 1er avril 2019' ]; //or:
+		yield 'Day approximate' => [ '2019-04-01~', 'le 1er avril 2019 environ' ];
```

As you see, there's no common format for ranges, the prepositions, articles (and contractions of preposition+article or articles with apostrophes before a vowel) depend on the precision (alternatives can also use appended adverbs like "environ"); and all strings above should have a leading lowercase letter.

Thes phenomenoms also apply in Italian and Spanish and many other languages.

**Comment by verdy-p** [comment]
We shuold note that EDTF deviates from CLDR only because "raw" values use additional delimiters that are still not specified in ISO 8601 (".." for ranges/intervals, or "%", "~", and "?" for uncertainty and "," for list of values; it had "()" also for subenemarations on some elements, but you deprecated them by adding "left/right" semantics for uncertainty qualifiers). But CLDR has full support for translation of ranges/intervals, variable precision for individual dates.

ETF also defined some "magic" values for "pseudo-months" representing seasons, quarters of years, quadrimestres, and half-years. In CLDR they are using another format (e.g. "H1" and "H2" for half-years, "Q1" to "Q4" for quarters, it also adds "W1 to W53" for weeks in the year, inherited from ISO 8601 but that EDTF still forgot to specify).

Such extensions could be added in CLDR (by adding a request to them). And possibly integrated in its "root" locale, or a separate special locale (like "POSIX", or "C" in legacy standard i18n libraries for C/C++), if there's a need to deviate (for example CLDR uses en-dashes rather than ".." for its root locale, and some locales for actual languages may change en-dashes with or without surrounding non-breaking spaces, depending on the number of date elements that they link together in the range). CLDR however has standardized translated items without forcing the leading capital.
